version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "--- Cleaning & Installing Maven ---"
      - mvn clean install -DskipTests=true

  build:
    commands:
      - echo "--- Build complete ---"

  post_build:
    commands:
      - echo "--- Listing target directory ---"
      - ls -lh target/
      - echo "--- Copying JAR to root ---"
      - cp target/*.jar .
      - echo "--- Listing current directory ---"
      - ls -lh .

artifacts:
  files:
    - *.jar
    - Procfile
  base-directory: .