version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -DskipTests=true
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/animal-marketplace-0.0.1-SNAPSHOT.jar
  discard-paths: yes