version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building Spring Boot application...
      - mvn clean package -DskipTests
      - mkdir app
      - cp target/animal-marketplace-0.0.1-SNAPSHOT.jar app/
      - echo 'web: java -jar animal-marketplace-0.0.1-SNAPSHOT.jar' > app/Procfile
  post_build:
    commands:
      - echo Packaging application...
      - cd app && zip -r ../application.zip .
artifacts:
  files:
    - application.zip
